services:
  power-dash:
    image: ygelfand/power-dash:latest
    container_name: power-dash
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      # Optional: Mount config file if you prefer it over env vars
      # - ./power-dash.yaml:/etc/power-dash/power-dash.yaml
    environment:
      - POWER_DASH_PASSWORD=YOUR_GATEWAY_PASSWORD
      - POWER_DASH_ENDPOINT=https://192.168.91.1/
      - TZ=America/Los_Angeles # Set your timezone
